const ChemicalActionTypes = {
	GET_CHEMICALS_REQUEST: 'GET_CHEMICALS_REQUEST',
	GET_CHEMICALS_SUCCESS: 'GET_CHEMICALS_SUCCESS',
	GET_CHEMICALS_FAIL: 'GET_CHEMICALS_FAIL',

	CREATE_CHEMICAL_REQUEST: 'CREATE_CHEMICAL_REQUEST',
	CREATE_CHEMICAL_SUCCESS: 'CREATE_CHEMICAL_SUCCESS',
	CREATE_CHEMICAL_FAIL: 'CREATE_CHEMICAL_FAIL',

	CHANGE_PAGE_SIZE: 'CHANGE_PAGE_SIZE',
};

export default ChemicalActionTypes;